name: Android CD

on:
  push:
    branches:
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Update Fastlane
      run: |
        bundle install
        bundle exec fastlane -v
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Download secrets
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
         scripts/download_s3.sh gradle.properties > gradle.properties
         scripts/download_s3.sh google-services.json > app/google-services.json
         scripts/download_s3.sh emitron_keystore.jks > emitron_keystore.jks
         scripts/download_s3.sh GooglePlayStore/google-play.json > google-play.json
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Upload app to Playstore
      run: bundle exec fastlane deploy

